const exams={
GCP:{name:"GCP Associate Cloud Engineer",questions:[
["A team needs to run a stateless HTTP container without managing a Kubernetes cluster. Which service fits? ",["Cloud Run","Cloud Storage","BigQuery","Cloud DNS"],0,"Cloud Run runs containers as a managed service without requiring you to manage a Kubernetes cluster."],
["Which IAM approach follows the principle of least privilege?",["Grant only required permissions","Give Owner to every developer","Use one shared account","Make the resource public"],0,"Least privilege means granting only the permissions required to perform the task."],
["In GKE, which object gives a stable network endpoint for a group of Pods?",["Service","ConfigMap","Secret","Namespace"],0,"A Kubernetes Service provides a stable virtual IP and DNS name for a selected set of Pods."],
["What is the main purpose of a Terraform module?",["Reuse infrastructure configuration","Store container images","Monitor CPU usage","Create Kubernetes Pods directly"],0,"Terraform modules package reusable infrastructure configuration so it can be used consistently across environments."],
["Which Google Cloud service is designed for storing and managing container images and other artifacts?",["Artifact Registry","Cloud DNS","Cloud SQL","Cloud Scheduler"],0,"Artifact Registry is Google's managed service for storing and managing packages and container images."],
["Which GCP resource is used to logically group resources for access control and billing?",["Project","Subnet","Zone","Firewall rule"],0,"Projects are the fundamental organizing boundary for many Google Cloud resources, IAM and billing."],
["Which GKE component runs on each node and manages containers?",["kubelet","Cloud Router","Cloud NAT","Cloud Scheduler"],0,"The kubelet is the Kubernetes node agent that ensures containers described by Pods are running."],
["What does a regional managed instance group provide?",["VM instances distributed across zones in a region","Only one VM","A Kubernetes namespace","A Cloud Storage bucket"],0,"Regional managed instance groups distribute VMs across multiple zones in a region for higher availability."],
["Which service provides object storage in Google Cloud?",["Cloud Storage","Cloud SQL","Filestore","Memorystore"],0,"Cloud Storage is Google's managed object storage service."],
["Which GCP service is a managed relational database?",["Cloud SQL","Cloud Storage","Pub/Sub","Cloud CDN"],0,"Cloud SQL provides managed MySQL, PostgreSQL and SQL Server databases."],
["What does Cloud NAT primarily allow?",["Private resources to make outbound internet connections","Internet users to directly reach private VMs","Pods to bypass IAM","Buckets to become public"],0,"Cloud NAT enables resources without external IP addresses to make outbound connections to the internet."],
["Which service is used for asynchronous messaging between applications?",["Pub/Sub","Cloud DNS","Cloud Armor","Cloud Storage"],0,"Pub/Sub is a managed messaging service for asynchronous, decoupled communication."],
["What is a VPC subnet associated with?",["A region","A project only","A single VM","A billing account"],0,"Google Cloud VPC subnets are regional resources."],
["Which service helps protect applications from Layer 7 attacks and DDoS threats?",["Cloud Armor","Cloud Storage","Cloud SQL","Cloud Scheduler"],0,"Cloud Armor provides application-layer protection and DDoS defense for supported Google Cloud workloads."],
["What does a GKE Deployment primarily manage?",["Desired state and rollout of replicated Pods","DNS zones","Cloud Storage objects","IAM policies"],0,"A Deployment manages ReplicaSets and supports declarative updates and rollouts for Pods."],
["Which tool is commonly used to interact with Kubernetes clusters from a terminal?",["kubectl","gcloud storage","terraform fmt","gsutil only"],0,"kubectl is the standard Kubernetes command-line client."],
["Which Google Cloud service provides centralized logging?",["Cloud Logging","Cloud DNS","Cloud Build","Cloud Deploy"],0,"Cloud Logging collects and lets you query logs from Google Cloud and supported applications."],
["What is the purpose of a GCP service account?",["Provide an identity for workloads or applications","Replace a VPC","Store secrets as plain text","Create a billing account"],0,"Service accounts are identities intended for workloads and applications rather than human users."],
["Which service builds container images and runs CI/CD build steps?",["Cloud Build","Cloud DNS","Cloud SQL","Cloud NAT"],0,"Cloud Build executes build steps and can build container images and other artifacts."],
["What does a firewall rule in a VPC control?",["Network traffic to or from VM instances","IAM permissions for users","Container image tags","Cloud billing exports"],0,"VPC firewall rules control allowed or denied network traffic for applicable VM interfaces."]
]},
CKA:{name:"Certified Kubernetes Administrator",questions:[
["Which command lists Pods in every namespace?",["kubectl get pods -A","kubectl get pods","kubectl list pods","kubectl pods"],0,"The -A/--all-namespaces flag requests resources across all namespaces."],
["Which Kubernetes object provides stable networking for a set of Pods?",["Service","Deployment","ConfigMap","Job"],0,"A Service exposes a stable virtual endpoint for selected Pods."],
["Which component stores Kubernetes cluster state?",["etcd","kubelet","CoreDNS","containerd"],0,"etcd is the distributed key-value store used by Kubernetes for cluster state."],
["What is a Kubernetes namespace mainly used for?",["Logical isolation and organization","Replacing nodes","Encrypting images","Creating cloud accounts"],0,"Namespaces provide a scope for names and a way to organize and isolate resources within a cluster."],
["Which command shows detailed information and events for a Pod?",["kubectl describe pod <name>","kubectl show pod <name>","kubectl inspect pod <name>","kubectl debug pod <name>"],0,"kubectl describe displays detailed resource information and recent events."],
["Which object maintains a requested number of identical Pods?",["Deployment","ConfigMap","ServiceAccount","Ingress"],0,"A Deployment manages ReplicaSets to maintain the desired number of Pod replicas."],
["Which command displays nodes in a cluster?",["kubectl get nodes","kubectl nodes","kubectl list nodes","kubectl show nodes"],0,"kubectl get nodes lists the nodes registered with the cluster."],
["What does a readiness probe affect?",["Whether a Pod is considered ready to receive traffic","Whether a node is created","Whether an image is built","Whether a Secret is encrypted"],0,"Readiness determines whether a container is ready to receive traffic from Services."],
["Which component assigns Pods to nodes?",["kube-scheduler","kubelet","kube-proxy","CoreDNS"],0,"The kube-scheduler selects suitable nodes for unscheduled Pods."],
["What does kube-proxy primarily help implement?",["Service networking rules","Container image builds","Persistent disk snapshots","API authentication"],0,"kube-proxy maintains network rules that implement Service connectivity on nodes."],
["Which resource stores non-sensitive configuration?",["ConfigMap","Secret","Service","Ingress"],0,"ConfigMaps store configuration data that is not intended to be confidential."],
["Which command shows the current cluster contexts?",["kubectl config get-contexts","kubectl get contexts","kubectl contexts","kubectl show config"],0,"kubectl config get-contexts lists contexts in the kubeconfig."],
["What is a DaemonSet designed to do?",["Run a Pod on selected or every eligible node","Create one-time Jobs","Expose a database","Store cluster state"],0,"DaemonSets ensure a copy of a Pod runs on nodes matching their scheduling rules."],
["What is a PersistentVolume (PV)?",["Cluster storage provisioned for use by workloads","A Pod template","A network policy","A container image"],0,"A PersistentVolume represents storage available to the cluster."],
["What does a PersistentVolumeClaim request?",["Storage with specified requirements","A Kubernetes user","A node","A container image"],0,"A PVC is a request for storage by a workload."],
["Which object controls allowed network traffic between Pods?",["NetworkPolicy","ConfigMap","Secret","ServiceAccount"],0,"NetworkPolicy defines rules for allowed ingress and egress traffic to selected Pods."],
["Which command applies a manifest declaratively?",["kubectl apply -f file.yaml","kubectl run -f file.yaml","kubectl create-file file.yaml","kubectl manifest file.yaml"],0,"kubectl apply creates or updates resources from a manifest declaratively."],
["Which Kubernetes object stores sensitive configuration data?",["Secret","ConfigMap","Service","Namespace"],0,"Secrets are designed to hold sensitive data such as credentials and tokens."],
["What does a Service of type LoadBalancer generally provide?",["External load-balancing access where supported","A new namespace","A storage volume","A CronJob"],0,"LoadBalancer Services request external load-balancing integration from the underlying platform."],
["Which command is useful for viewing recent cluster events?",["kubectl get events","kubectl events-only","kubectl show events","kubectl list-events"],0,"kubectl get events displays Event resources, which are useful for troubleshooting."]
]},
CKAD:{name:"Certified Kubernetes Application Developer",questions:[
["Which object stores non-sensitive configuration data?",["ConfigMap","Secret","Service","Ingress"],0,"ConfigMaps store non-confidential configuration values."],
["Which object is intended for sensitive values?",["Secret","ConfigMap","Service","Ingress"],0,"Secrets are intended for sensitive configuration such as passwords and tokens."],
["Which probe determines whether a container is ready to receive traffic?",["Readiness probe","Startup probe","Liveness probe","Node probe"],0,"A readiness probe controls whether the container is considered ready to receive traffic."],
["Which resource defines HTTP routing rules in the traditional Ingress model?",["Ingress","ConfigMap","Job","DaemonSet"],0,"Ingress defines HTTP/HTTPS routing rules for external access to Services."],
["Which command creates a Deployment named web using nginx?",["kubectl create deployment web --image=nginx","kubectl deploy web nginx","kubectl run deployment web nginx","kubectl create pod web --deployment nginx"],0,"kubectl create deployment NAME --image=IMAGE creates a Deployment from the command line."],
["Which command creates a ConfigMap from a literal value?",["kubectl create configmap app-config --from-literal=mode=prod","kubectl create map app-config mode=prod","kubectl configmap app-config mode=prod","kubectl apply configmap app-config mode=prod"],0,"The --from-literal option creates a ConfigMap key/value directly from the command line."],
["What is the purpose of a liveness probe?",["Determine whether a container should be restarted","Decide whether traffic should be sent","Create a node","Build an image"],0,"A liveness probe can indicate that a container is unhealthy and should be restarted."],
["What is the purpose of a startup probe?",["Give slow-starting containers time to initialize","Expose a Service externally","Create a Secret","Schedule a node"],0,"Startup probes protect slow-starting applications from being restarted by liveness checks before initialization completes."],
["Which field defines the container image in a Pod spec?",["image","containerImage","imageName","repository"],0,"The containers[].image field specifies the image to run."],
["Which object can expose a Deployment internally within the cluster?",["Service","ConfigMap","Secret","CronJob"],0,"A ClusterIP Service is the default internal networking mechanism for exposing selected Pods."],
["What does kubectl exec allow you to do?",["Execute a command inside a running container","Create a cluster","Build an image","Change a node's machine type"],0,"kubectl exec runs a command in a container of a running Pod."],
["Which resource is used for scheduled batch work?",["CronJob","Service","Ingress","ConfigMap"],0,"A CronJob creates Jobs on a repeating schedule."],
["Which resource represents a one-off batch workload?",["Job","Service","Ingress","Secret"],0,"A Job runs Pods to completion and tracks successful completion."],
["What does a HorizontalPodAutoscaler change?",["The number of Pod replicas based on metrics","The VM machine type","The container image digest","The namespace name"],0,"An HPA adjusts the number of Pod replicas based on configured metrics."],
["Which command can show container logs?",["kubectl logs <pod>","kubectl output <pod>","kubectl print logs <pod>","kubectl show-log <pod>"],0,"kubectl logs retrieves logs from containers in Pods."],
["Which field is commonly used to pass a ConfigMap value into an environment variable?",["env","volumeOnly","config","variables"],0,"The env section can reference ConfigMap keys through valueFrom.configMapKeyRef."],
["Which Kubernetes resource packages an application as a desired set of Pods with rollout behavior?",["Deployment","Service","ConfigMap","Namespace"],0,"Deployments provide declarative updates and rollout management for replicated Pods."],
["What does a Service selector do?",["Selects Pods that should receive Service traffic","Selects a node OS","Selects a container registry","Selects a namespace"],0,"Service selectors match Pod labels to determine the endpoints receiving traffic."],
["Which command creates a Secret from a literal value?",["kubectl create secret generic app-secret --from-literal=password=demo","kubectl create secret app-secret password=demo","kubectl secret generic app-secret password=demo","kubectl make-secret app-secret password=demo"],0,"kubectl create secret generic with --from-literal creates a Secret key/value."],
["What is a Pod?",["The smallest deployable unit in Kubernetes, containing one or more containers","A Kubernetes cluster","A container registry","A cloud project"],0,"A Pod is the smallest deployable unit in Kubernetes and can contain one or more closely coupled containers."]
]}};

const refs={
GCP:[
["Cloud Run documentation","https://cloud.google.com/run/docs"],["IAM overview","https://cloud.google.com/iam/docs/overview"],["GKE Services","https://cloud.google.com/kubernetes-engine/docs/concepts/service"],["Terraform modules","https://developer.hashicorp.com/terraform/language/modules"],["Artifact Registry documentation","https://cloud.google.com/artifact-registry/docs"],["Google Cloud resource hierarchy","https://cloud.google.com/resource-manager/docs/cloud-platform-resource-hierarchy"],["GKE architecture","https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture"],["Managed instance groups overview","https://cloud.google.com/compute/docs/instance-groups"],["Cloud Storage documentation","https://cloud.google.com/storage/docs"],["Cloud SQL documentation","https://cloud.google.com/sql/docs"],["Cloud NAT documentation","https://cloud.google.com/nat/docs/overview"],["Pub/Sub documentation","https://cloud.google.com/pubsub/docs/overview"],["VPC networks and subnets","https://cloud.google.com/vpc/docs/vpc#vpc_networks_and_subnets"],["Cloud Armor documentation","https://cloud.google.com/armor/docs"],["GKE Deployments","https://cloud.google.com/kubernetes-engine/docs/concepts/deployment"],["kubectl reference","https://kubernetes.io/docs/reference/kubectl/"],["Cloud Logging documentation","https://cloud.google.com/logging/docs"],["Service accounts overview","https://cloud.google.com/iam/docs/service-account-overview"],["Cloud Build documentation","https://cloud.google.com/build/docs/overview"],["VPC firewall rules","https://cloud.google.com/firewall/docs/firewalls"]
],
CKA:[
["kubectl get reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_get/"],["Kubernetes Services","https://kubernetes.io/docs/concepts/services-networking/service/"],["etcd documentation","https://etcd.io/docs/"],["Namespaces","https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"],["kubectl describe reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_describe/"],["Deployments","https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"],["kubectl get nodes","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_get/"],["Liveness, readiness and startup probes","https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/"],["kube-scheduler","https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/"],["kube-proxy","https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/"],["ConfigMaps","https://kubernetes.io/docs/concepts/configuration/configmap/"],["kubectl config reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_config/"],["DaemonSets","https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/"],["PersistentVolumes","https://kubernetes.io/docs/concepts/storage/persistent-volumes/"],["PersistentVolumeClaims","https://kubernetes.io/docs/concepts/storage/persistent-volumes/"],["NetworkPolicies","https://kubernetes.io/docs/concepts/services-networking/network-policies/"],["kubectl apply reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_apply/"],["Secrets","https://kubernetes.io/docs/concepts/configuration/secret/"],["Service type LoadBalancer","https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer"],["Kubernetes Events","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_events/"]
],
CKAD:[
["ConfigMaps","https://kubernetes.io/docs/concepts/configuration/configmap/"],["Secrets","https://kubernetes.io/docs/concepts/configuration/secret/"],["Liveness, readiness and startup probes","https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/"],["Ingress","https://kubernetes.io/docs/concepts/services-networking/ingress/"],["kubectl create deployment reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_deployment/"],["kubectl create configmap reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_configmap/"],["Liveness probes","https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/"],["Startup probes","https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/"],["Pod container images","https://kubernetes.io/docs/concepts/containers/images/"],["Services","https://kubernetes.io/docs/concepts/services-networking/service/"],["kubectl exec reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_exec/"],["CronJobs","https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/"],["Jobs","https://kubernetes.io/docs/concepts/workloads/controllers/job/"],["Horizontal Pod Autoscaling","https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/"],["kubectl logs reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_logs/"],["Define environment variables","https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/"],["Deployments","https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"],["Service selectors","https://kubernetes.io/docs/concepts/services-networking/service/"],["kubectl create secret reference","https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic/"],["Pods","https://kubernetes.io/docs/concepts/workloads/pods/"]
]};

let currentKey=null,current=null,index=0,answers=[],seconds=2700,timerId=null;
const cards=document.getElementById("cards");

function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function buildCards(){cards.innerHTML=Object.entries(exams).map(([k,e])=>`<article class="cert-card"><span class="cert-code">${k}</span><h2>${e.name}</h2><p>20 original practice questions with explanations and a timed mock-exam flow.</p><button class="start-button" onclick="start('${k}')">Start mock exam →</button></article>`).join("")}
function start(k){currentKey=k;current=exams[k];index=0;answers=Array(current.questions.length).fill(null);seconds=2700;cards.hidden=true;document.getElementById("practice").hidden=false;startTimer();render()}
function startTimer(){clearInterval(timerId);updateTimer();timerId=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timerId);finish()}},1000)}
function updateTimer(){const m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");const el=document.getElementById("timer");el.textContent=m+":"+s;el.classList.toggle("warning",seconds<=300)}
function render(){const q=current.questions[index];document.getElementById("title").textContent=current.name;document.getElementById("progress").textContent=`Question ${index+1} of ${current.questions.length}`;document.getElementById("score-live").textContent=`${answers.filter(x=>x!==null).length} answered`;document.getElementById("progress-bar").style.width=((index+1)/current.questions.length*100)+"%";document.getElementById("question").innerHTML=`<div class="question-text">${escapeHtml(q[0])}</div>`;document.getElementById("options").innerHTML=q[1].map((x,i)=>`<button class="option ${answers[index]===i?"selected":""}" onclick="choose(${i})"><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${escapeHtml(x)}</span></button>`).join("");document.getElementById("next-button").textContent=index===current.questions.length-1?"Submit exam →":"Next question →"}
function choose(i){answers[index]=i;render()}
function next(){if(answers[index]===null){alert("Please choose an answer first.");return}if(index<current.questions.length-1){index++;render()}else finish()}
function finish(){clearInterval(timerId);const correct=answers.reduce((n,a,i)=>n+(a===current.questions[i][2]?1:0),0);const pct=Math.round(correct/current.questions.length*100);document.getElementById("progress-bar").style.width="100%";document.getElementById("score-live").textContent=`${correct}/${current.questions.length} correct`;document.getElementById("question").innerHTML=`<div class="result"><div class="eyebrow">MOCK EXAM COMPLETE</div><div class="result-score">${pct}%</div><p>You got <strong>${correct} of ${current.questions.length}</strong> questions correct.</p></div>`;document.getElementById("options").innerHTML=`<div class="review">${current.questions.map((q,i)=>{const ok=answers[i]===q[2],ref=refs[currentKey][i];return `<div class="review-item"><strong>Q${i+1}. ${escapeHtml(q[0])}</strong><p class="${ok?"correct":"incorrect"}">${ok?"✓ Correct":"✗ Incorrect"} · Your answer: ${answers[i]===null?"Not answered":escapeHtml(q[1][answers[i]])}</p><p><strong>Correct answer:</strong> ${escapeHtml(q[1][q[2]])}</p><div class="answer-explanation"><strong>Why this answer?</strong><p>${escapeHtml(q[3])}</p></div><div class="question-reference"><strong>📚 Reference</strong><p><a href="${ref[1]}" target="_blank" rel="noopener noreferrer">${escapeHtml(ref[0])} ↗</a></p></div></div>`}).join("")}</div>`;document.getElementById("next-button").textContent="Retake exam";document.getElementById("next-button").onclick=()=>start(currentKey)}
function backToCerts(){clearInterval(timerId);document.getElementById("practice").hidden=true;cards.hidden=false;document.getElementById("next-button").onclick=next}
buildCards();
